In [1]:
import numpy as np

In [4]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [2]:
np.ones((5,5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [3]:
np.empty((7,7),dtype=int)

array([[4128860, 6029375, 3801155, 5570652, 6619251, 7536754, 7602268],
       [6815845, 6619251, 4259932, 6357102, 7274595, 6553710, 3342433],
       [7077980, 6422633, 7536732, 7602281, 2949221, 6357104, 7012451],
       [6750305, 7536741, 7340124, 6750329, 6619245, 7602286, 6029427],
       [7602291, 7078009, 7536741, 6226012, 7340127, 6488185, 6488161],
       [6619240, 6226015, 6553692, 6684773, 7667809, 7602284, 6488110],
       [7929968, 6815860, 7209071, 3342381, 3014711, 7929968,      99]])

In [6]:
l=[1,4,6,7]
%time np.array(l)**4

Wall time: 0 ns


array([   1,  256, 1296, 2401], dtype=int32)

In [5]:
np.arange(1,100,10)

TypeError: arange: scalar arguments expected instead of a tuple.

In [10]:
x=np.arange(1,100,10)
x.shape

(10,)

In [15]:
z=np.zeros((10,10,10))
z.shape

(10, 10, 10)

In [12]:
z.reshape((2,2,5,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [14]:
z.ndim

2

In [26]:
a=np.random.randn((10))

In [27]:
d=np.random.randn((10))

In [29]:
a+d

array([ 3.24228125,  1.77586658,  2.5686844 ,  0.6795262 ,  1.15663127,
        0.3600757 ,  1.26471106, -0.09087976,  0.53283934,  0.88177399])

In [30]:
2/d

array([  1.57204237,   3.90822458,   2.66654851,  24.97038537,
         1.01013672,  -9.50294671,   4.27678095,  -3.93843895,
       -23.59206957,   1.9598033 ])

In [31]:
a>1

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [33]:
a[a>0]

array([1.97005091, 1.26412527, 1.81865117, 0.59943132, 0.57053674,
       0.79706962, 0.41693565, 0.61761359])

In [18]:
x=np.array([1,7,9,8,4])

In [20]:
x[1]

7

In [22]:
x[x>5]

array([7, 9, 8])

In [37]:
x[[1,3]]

array([7, 8])

In [32]:
x=np.random.randn(10,2)
x.shape

(10, 2)

In [33]:
x[0]

array([ 0.88571009, -0.42226848])

In [34]:
x[0][1]

-0.422268477973477

In [42]:
x[1:10:2,0:2]

array([[-0.31581597,  1.03944625],
       [-1.88548925, -0.19992578],
       [ 0.45773521,  0.34428948],
       [ 0.58145657, -0.60659004],
       [ 0.67676113, -1.64026512]])

In [35]:
x=np.ones((5,5))

In [36]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
x[1:-1,1:-1]=0

In [46]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
x=np.array([10,9,5,6,11])
np.sqrt(x)#square root

array([3.16227766, 3.        , 2.23606798, 2.44948974, 3.31662479])

In [60]:
np.power(x,3)#power of x by 3

array([1000,  729,  125,  216, 1331], dtype=int32)

In [64]:
y=[7,6,1,9,21]
np.minimum(x,y)

array([ 7,  6,  1,  6, 11])

In [65]:
np.maximum(x,y)

array([10,  9,  5,  9, 21])

# np.where()

In [69]:
salary=np.array([0,10000,5000,50000,100000])

In [70]:
np.where(salary<=25000,'Doobke Mar',salary)

array(['Doobke Mar', 'Doobke Mar', 'Doobke Mar', '50000', '100000'],
      dtype='<U11')

In [72]:
np.where(salary<=25000,False,True)

array([False, False, False,  True,  True])

# Mathematical and Statistical Method

In [47]:
x=np.array([5,91,54,6,8,55])
x.mean()
x

array([ 5, 91, 54,  6,  8, 55])

In [3]:
x.cumsum()

array([10, 15, 22, 28, 43], dtype=int32)

In [4]:
x.cumprod()

array([   10,    50,   350,  2100, 31500], dtype=int32)

In [5]:
y=x>6

In [45]:
x

array([ 5,  6,  8, 55])

In [46]:
x.sum()

74

In [8]:
y.any()

True

In [9]:
y.all()

False

In [10]:
y=x>7

In [11]:
y

array([ True, False, False, False,  True])

In [12]:
y.sum()

2

In [13]:
y.any()

True

In [14]:
y.all()

False

In [56]:
x.sort(axis=0)
x

array([ 5,  6,  8, 54, 55, 91])

In [50]:
np.unique(x)

array([ 5,  6,  8, 54, 55, 91])

# Save and load files

In [18]:
#np.save(filename.npy,array)
#np.load(filename.npy)
#np.savez(filename.npz,array1,array2)

In [19]:
x=[1,3,5,7]
y=[7,9,11]

In [20]:
np.save('testx',x)

In [22]:
loadx=np.load('testx.npy')

In [23]:
loadx

array([1, 3, 5, 7])

In [24]:
np.savez('testxy',x,y)

In [25]:
loadxy=np.load('testxy.npz')

In [26]:
loadxy

In [27]:
np.array(loadxy)

array(['arr_0', 'arr_1'], dtype='<U5')

# Linear Algebra

In [7]:
x=np.random.randn(3,2)
y=np.random.randn(2,3)

In [10]:
t=np.array([1,2,3,4,5])
p=np.array([5,6,7,8,9])
t.dot(p)

115

In [29]:
x.dot(y)

array([[-0.28982465,  0.37140461, -4.66875533],
       [ 0.45491757,  0.09817026, -0.2428344 ],
       [ 0.13718124, -0.21652068,  2.66251578]])

In [30]:
x.transpose()

array([[ 1.98647827,  0.10071891, -1.13270084],
       [-1.19314211,  0.78758274,  0.62962919]])

In [31]:
x.trace()

2.774061009816347

In [19]:
x=np.random.randn(3,2)

In [35]:
b=np.ones((3,2))
display(b.T)
b.reshape((2,3,1))

array([[1., 1., 1.],
       [1., 1., 1.]])

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [35]:
x.reshape((2,2,5))

array([[[ 0.40785252, -0.63143838,  2.50823112, -1.47195204,
         -0.82675994],
        [ 0.7730734 , -0.64737751, -0.34973743, -0.01303251,
         -0.54263137]],

       [[ 0.25749872,  0.25880172, -0.47871589, -1.09995047,
         -0.6768662 ],
        [ 0.26496297, -0.41003019,  1.97511252, -0.95511569,
          1.77150432]]])

In [36]:
x.reshape((2,2,5),order='F')#column major order

array([[[ 0.40785252, -0.63143838,  2.50823112, -1.47195204,
         -0.82675994],
        [ 0.25749872,  0.25880172, -0.47871589, -1.09995047,
         -0.6768662 ]],

       [[ 0.7730734 , -0.64737751, -0.34973743, -0.01303251,
         -0.54263137],
        [ 0.26496297, -0.41003019,  1.97511252, -0.95511569,
          1.77150432]]])

In [37]:
x.reshape((2,2,-1))

array([[[ 0.40785252, -0.63143838,  2.50823112, -1.47195204,
         -0.82675994],
        [ 0.7730734 , -0.64737751, -0.34973743, -0.01303251,
         -0.54263137]],

       [[ 0.25749872,  0.25880172, -0.47871589, -1.09995047,
         -0.6768662 ],
        [ 0.26496297, -0.41003019,  1.97511252, -0.95511569,
          1.77150432]]])

In [38]:
x.ravel()#create one dimention array

array([ 0.40785252, -0.63143838,  2.50823112, -1.47195204, -0.82675994,
        0.7730734 , -0.64737751, -0.34973743, -0.01303251, -0.54263137,
        0.25749872,  0.25880172, -0.47871589, -1.09995047, -0.6768662 ,
        0.26496297, -0.41003019,  1.97511252, -0.95511569,  1.77150432])

In [39]:
x.flatten()#create one dimention array

array([ 0.40785252, -0.63143838,  2.50823112, -1.47195204, -0.82675994,
        0.7730734 , -0.64737751, -0.34973743, -0.01303251, -0.54263137,
        0.25749872,  0.25880172, -0.47871589, -1.09995047, -0.6768662 ,
        0.26496297, -0.41003019,  1.97511252, -0.95511569,  1.77150432])

In [57]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [61]:
x = np.array((3, 5), dtype=np.float32)
np.asarray([5,4], dtype=np.float32)


array([5., 4.], dtype=float32)

In [6]:
display(np.ones(3))
display(np.zeros_like([[7,6,6]]))

array([1., 1., 1.])

array([[0, 0, 0]])

In [63]:
np.full_like(15,14)

array(14)

In [27]:
np.array([3,3])

array([3, 3])

In [53]:
num=np.array([0,55,4,68,5])
num


array([ 0, 55,  4, 68,  5])

In [59]:
np.where(num<=6 , 2500 , num)

array([2500,   55, 2500,   68, 2500])

In [119]:
num=np.arange(3,10)
display(num.sum())
display(num.cumsum())
display(num.cumprod())

42

array([ 3,  7, 12, 18, 25, 33, 42], dtype=int32)

array([     3,     12,     60,    360,   2520,  20160, 181440],
      dtype=int32)

In [120]:
display(num)
display(num.sum())
display(num.any())
display(num.all())

array([3, 4, 5, 6, 7, 8, 9])

42

True

True

In [121]:
np.unique(num)

array([3, 4, 5, 6, 7, 8, 9])

In [69]:
s=np.zeros((3,5))
display(s)
s.reshape((5,3), order='C')

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
s.flatten('C')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
np.ravel(s,order='C')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [73]:
np.concatenate(s,axis=0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [156]:
s.ndim

2

In [157]:
s

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [67]:
s1=np.array([1,2,3,4,5])
s2=np.array([6,7,8,9,10])

display(np.vstack((s1,s2)))
display(np.hstack((s1,s2)))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
display(np.r_[s1, s2])
np.c_[np.r_[s1, s2]]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [181]:
np.split(s1,[1,3])

[array([1]), array([2, 3]), array([4, 5])]